version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nummm
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: FirstExampleDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "7711:3306"
    restart: always
