spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourDatabaseName
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mongodb:
    url: mongodb://localhost:27017/overspecialised

server:
  port: 7700
